image: alpine:latest

stages:
  - test
  - demo

test:
  stage: test
  script:
  - apk --update add python git openssh py-pip && \
    pip install --upgrade pip==9.0.3 && \
    pip --no-cache-dir install pyyaml jinja2
  - git clone -b $CI_COMMIT_REF_NAME https://_gitlab@git.juniper.net/NITA/nita-cli.git
  - cd nita-cli/
  - sh install.sh
  - nita ?
  - nita cli version
  tags:
    - docker

trigger_demo:
  stage: demo
  script:
    - apk --update add curl
    - curl -X POST -F token=$VN_TOKEN -F ref=master https://git.juniper.net/api/v4/projects/1600/trigger/pipeline
  tags:
    - docker
  only:
    - master
